<?php
/* Generated by neoan3-cli */

namespace Neoan3\Model\Invoice;

use Neoan3\Provider\MySql\Database;
use Neoan3\Provider\Model\Model;
use Neoan3\Provider\MySql\Transform;

/**
 * Class InvoiceModel
 * @package Neoan3\Model\Invoice
 * @method static get(string $id)
 * @method static create(array $modelArray)
 * @method static update(array $modelArray)
 * @method static find(array $conditionArray)
 * @method static delete(string $id, bool $hard = false)
 */

class InvoiceModel implements Model{

    /**
     * @var Database|null
     */
    private static ?Database $db = null;

    /**
     * @param $method
     * @param $args
     * @return mixed
     */
    public static function __callStatic($method, $args)
    {
        if(!method_exists(self::class, $method)){
            $transform = new Transform('invoice', self::$db);
            return $transform->$method(...$args);
        } else {
            return self::$method(...$args);
        }
    }
    public static function search($keyword): array
    {
        $values = [
            'pure' => $keyword,
            'keyword' => "%$keyword%"
        ];
        $sql = '>SELECT id FROM invoice i LEFT JOIN client c ON c.id = i.client_id WHERE i.delete_date IS NULL AND (c.name LIKE {{keyword}} OR i.id = UNHEX({{pure}}) OR i.notes LIKE {{keyword}})';
        $ids = self::$db->smart($sql, $values);
        $results = [];
        foreach ($ids as $id){
            $results[] = self::get($id['id']);
        }
        return $results;
    }

    /**
     * @param array $providers
     */
    public static function init(array $providers)
    {
        foreach ($providers as $key => $provider){
            if($key === 'db'){
                self::$db = $provider;
            }
        }
    }

}