<?php

namespace Neoan3\Component\Calendar;

use Neoan3\Frame\Smabi;
use Neoan3\Model\Calendar\CalendarModel;
use Neoan3\Provider\Auth\Authorization;
use Neoan3\Provider\Model\InitModel;

/**
 * Class CalendarController
 * @package Neoan3\Component\Calendar
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class CalendarController extends Smabi{

    /**
     * GET: api.v1/calendar
     * GET: api.v1/calendar/{id}
     * GET: api.v1/calendar?{query-string}
     * @param array $params
     * @return array
     */
    #[InitModel(CalendarModel::class)]
    #[Authorization('restrict')]
    function getCalendar(array $params = []): array
    {
        return CalendarModel::range($params['from']);
    }

    /**
     * POST: api.v1/calendar
     * @param array $body
     * @return array
     */
    #[InitModel(CalendarModel::class)]
    #[Authorization('restrict')]
    function postCalendar(array $body): array
    {
        return CalendarModel::create($body);
    }

    #[InitModel(CalendarModel::class)]
    #[Authorization('restrict')]
    function putCalendar(array $body): array
    {
        return CalendarModel::update($body);
    }
}
