<?php

namespace Neoan3\Component\Product;

use Neoan3\Frame\Smabi;
use Neoan3\Model\Product\ProductModel;
use Neoan3\Provider\Auth\Authorization;
use Neoan3\Provider\Model\InitModel;

/**
 * Class ProductController
 * @package Neoan3\Component\Product
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ProductController extends Smabi{

    /**
     * GET: api.v1/product
     * GET: api.v1/product/{id}
     * GET: api.v1/product?{query-string}
     * @param array $params
     * @return array
     */
    #[Authorization('restrict')]
    #[InitModel(ProductModel::class)]
    function getProduct(array $params = []): array
    {
        if(isset($params['find'])){
            return ProductModel::search($params['find']);
        }
        return [];
    }

    /**
     * POST: api.v1/product
     * @param array $body
     * @return array
     */
    #[Authorization('restrict')]
    #[InitModel(ProductModel::class)]
    function postProduct(array $body): array
    {
        return ProductModel::create($body);
    }
    /**
     * PUT: api.v1/product
     * @param array $body
     * @return array
     */
    #[Authorization('restrict')]
    #[InitModel(ProductModel::class)]
    function putProduct(array $body): array
    {
        return ProductModel::update($body);
    }
}
