<?php

namespace Neoan3\Component\Category;

use Neoan3\Frame\Smabi;

/**
 * Class CategoryController
 * @package Neoan3\Component\Category
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class CategoryController extends Smabi{

    /**
    * GET: api.v1/category
    * GET: api.v1/category/{id}
    * GET: api.v1/category?{query-string}
    * @param array $params
    * @return array
    */
    function getCategory(array $params = []): array
    {
        return $this->provider['db']->smart('> SELECT DISTINCT(category) as category, category as id FROM product WHERE category IS NOT NULL GROUP by category ORDER BY category');
    }

    /**
     * POST: api.v1/category
     * @param $body
     * @return array
     */
    function postCategory(array $body): array
    {
        return $body;
    }
}
